### ISSUE TITLE
[dependencies] manual install needed

### ISSUE THREAD

**Issue by Adafede** [soerendip/ms-peakonly#2]
Hi,

Dependencies have to be installed manually, which is not really optimal.

To help, here is a first list (probably more missing):

```
mamba install pytorch torchvision torchaudio -c pytorch

mamba install -c bioconda pymzml

mamaba install -c conda-forge bintrees 
``` 

Best

**Comment by sorenwacker** [comment]
Hi, 

I added the dependencies directly to the `setup.py` file. Now, all dependencies are installed with `pip install .`
