### ISSUE TITLE
[bug?] Retention times

### ISSUE THREAD

**Issue by Adafede** [soerendip/ms-peakonly#4]
Hi,

Tried a few analyses and looks like peaks are well detected but the retention time does not match at all. It looks like it only gives the very first time the *m/z* appears (not even in a peak).  I have no real idea where it might come from...Might be because of the experimental named tensors?

**Comment by sorenwacker** [comment]
Hi Adafede, 

what commands do you execute exactly and how do you compare the retention times?

**Comment by Adafede** [comment]
Hi @soerendip, 

just as in your readme:

`
from ms_peakonly import PeakOnly
from glob import glob
import pandas

fns = glob('/my/metabolomics/directory/*.mzML')

po = PeakOnly(model_dir='/my/model/directory/')

table = po.process(fns) 

table.to_csv(export_path)
`

all obtained m/z correspond to peaks but with an RT corresponding to the first occurrence of the m/z and not where the peak is located.

**Comment by sorenwacker** [comment]
Could you clarify what do you mean with _first occurrence_?

**Comment by Adafede** [comment]
Let’s say I extract the XIC for a given m/z, it will be made of a few points at very low intensity randomly distributed below noise starting from almost the begin of my LC run. I mean those points. Not the nice >15 points at high intensity with a higher retention time forming a peak…i can give you a file and the command if you Need

**Comment by sorenwacker** [comment]
Yes, that might be helpful. 

![image](https://user-images.githubusercontent.com/3391614/125492512-e549d871-8d83-4654-a24f-853911cf1705.png)

There is `rt_min` and `rt_max` which should be the beginning and the end of the peak. 

And based on visualization with a different program, those retention times look good in most cases: 
![image](https://user-images.githubusercontent.com/3391614/125492701-1518944a-42fc-4bbb-95bb-7acc18eb225b.png)

**Comment by Adafede** [comment]
Your table seems to illustrate well what I meant: almost all peaks are <0.5min. This should not be the case…those peaks probably are at a higher rt later in the chromatogram. Will attach a file later on

**Comment by sorenwacker** [comment]
You, mean in the table? The `_min` stands for _minimum_ not for _minute_. The output of `PeakOpt` is in _hours_ for some reason. Did you try to convert the numbers? I was also puzzled about this.

**Comment by Adafede** [comment]
Ohhhh wow! So That might be it! I knew it was minimum and maximum but thought it was in minutes, not in hours! Will then have to convert and check…Many thanks!

**Comment by Adafede** [comment]
was indeed because of hours <-> minutes, thanks a lot!
