### ISSUE TITLE
[bug] 'v cannot be empty'

### ISSUE THREAD

**Issue by Adafede** [soerendip/ms-peakonly#5]
Hi!

I just had the following:

```
line 843, in convolve
    raise ValueError('v cannot be empty')
```

It is probably due to https://github.com/Arseha/peakonly/blob/29e9af5bfa0e6b816ff15dcdc903b4c81412177c/processing_utils/matching.py#L320.

One way to fix it is detailed here: https://fixexception.com/numpy/v-cannot-be-empty/

Also tagging @Arseha in case!

Best,

**Comment by sorenwacker** [comment]
Thank you.
